### ISSUE TITLE
Утечка памяти / забытый деструктор

### ISSUE THREAD

**Issue by avasyukov** [d-qql/interfaceTree#2]
Если выполнить вот такой наивный main, то видна утечка памяти:
```
int main()
{
    Container* c = new tree();
    for(int i = 1; i < 10; i++)
        c->insert(i*i);
    delete c;
    return 0;
}
```
Забыт деструктор - подчистка памяти именно его работа. Его нужно добавить. Скорее всего, он заменит собой нынешний DeleteAll, но это смотрите сами.

**Comment by d-qql** [comment]
fixed

**Comment by avasyukov** [comment]
Подтверждаю, решено
